### PR TITLE
View post bookmarklet

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
**Changes**

Adds a [view post] to every single quote in the forums

**Reason for changes**
theres been a surge of them lately

sorry for the big amount of PRs

### CODE REVIEW

**Comment by Shluffy** [comment]
can't seem to get it to work - can you show it to use in action

**Comment by FunctionalMetatable** [comment]
> 
> 
> can't seem to get it to work - can you show it to use in action

strangely, it works in the console but not the bookmarklet

**Comment by Shluffy** [comment]
still not working for me

**Comment by FunctionalMetatable** [comment]
> 
> 
> still not working for me

which browser are you using

**Comment by Shluffy** [comment]
chrome beta (chrome os)

**Comment by xItzDiamondx** [comment]
Screenshot 2021-05-23 7 40 19 PM
Fix it then we'll reopen.

**Comment by FunctionalMetatable** [comment]
> Screenshot 2021-05-23 7 40 19 PM
> Fix it then we'll reopen.

you don't actually put it in the search bar because #56 removed the javascript: prefix. you have to manually put it in the console

**Comment by xItzDiamondx** [comment]
I clicked on it while i was in a scratch forumn

**Pull request closed without merging**
