### PR TITLE
add wiki in website

### LINKED ISSUE #147: Feature Request: Use the wiki page for this repository
**Feature**

use the wiki page

### PR DESCRIPTION
**Pull request by Shluffy**
resolves #147 
wip

### CODE REVIEW

**Comment by ZI-Youtuber** [comment]
https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/issues/147#issuecomment-854794398

**Review by ZI-Youtuber — CHANGES_REQUESTED** [review]
https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/issues/147#issuecomment-854796020


https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/issues/147#issuecomment-854794398

**Comment by ZI-Youtuber** [comment]
https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/issues/147 @Shluffy

**Comment by Shluffy** [comment]
@ZI-Youtuber i see it mentioned three times

**Pull request closed without merging**
