### PR TITLE
Structured json

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
**Changes**

Adds folders for bookmarklets. You won't need to add `javascript:` before the code now!

**Reason for changes**
they should

**Tests**

tested on fork

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
if merging please squish and merge

**Comment by xItzDiamondx** [comment]
> if merging please squish and merge

Says this when I try to squash / merge.
Screenshot 2021-05-22 2 39 03 PM
@FunctionalMetatable

**Comment by FunctionalMetatable** [comment]
> > if merging please squish and merge
> 
> Says this when I try to squash / merge.
> Screenshot 2021-05-22 2 39 03 PM
> @FunctionalMetatable

rip

guess @Shluffy / @gosoccerboy5 will have to do something

**Comment by xItzDiamondx** [comment]
i can, i have manage access

**Comment by xItzDiamondx** [comment]
Fixed it. Now it needs to get reviewed by @gosoccerboy5 and @Shluffy

**Review by gosoccerboy5 — APPROVED** [review]
Looks great! I would request that you use an absolute url since I can't fetch from my own filesystem, but I suppose you've made so many changes it would be hard to test locally, with an absolute url anyways.

**Review by Shluffy — CHANGES_REQUESTED** [review]
OPen project in turbowarp is by @gosoccerboy5

**Review by Shluffy — APPROVED** [review]
looks good now

**Pull request merged**
