### PR TITLE
Create 404.html

### LINKED ISSUE #9: Feature Request: 404 page.
I will get started on this.

### PR DESCRIPTION
**Pull request by Shluffy**
this has not been tested - I will test it soon

**Resolves**

Resolves #9 

**Changes**

adds 404 page

**Reason for changes**

cause it is good to have a 404 page

**Tests**

tested on my fork

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
tested locally, works.

**Comment by xItzDiamondx** [comment]
I'll merge.

**Review by gosoccerboy5 — CHANGES_REQUESTED** [review]
would appreciate some CSS.

also, use an absolute url like to the homepage, or at least "/index.html". "index.html" will not work when you're a couple directories deep

**Comment by Shluffy** [comment]
> I'll merge.

pls don't merge without an approving review

**Comment by Shluffy** [comment]
> would appreciate some CSS.
> 
> also, use an absolute url like to the homepage, or at least "/index.html". "index.html" will not work when you're a couple directories deep

I'll add relative url, and once we make a header and footer I will get to the css

**Comment by gosoccerboy5** [comment]
> I'll merge.

"From then on, gosoccerboy5 learned to share his full opinions at once so that people didn't merge PRs before he shared his review."

**Comment by gosoccerboy5** [comment]
> also, use an absolute url like to the homepage, or at least "/index.html". "index.html" will not work when you're a couple directories deep

wait im stupid, you used a base element. ignore that part

**Comment by xItzDiamondx** [comment]
> would appreciate some CSS.
> 
> also, use an absolute url like to the homepage, or at least "/index.html". "index.html" will not work when you're a couple directories deep

I think you need to put them in folders for that to happen

**Pull request merged**
