### PR TITLE
Patch 2: #53 Fixed and a few more updates.

### LINKED ISSUE #53: Feature Request: alert user if they have clicked a scratch bookmarklet not on scratch
**Feature**
alert user if they have clicked a scratch bookmarklet not on scratch

### PR DESCRIPTION
**Pull request by xItzDiamondx**
**Resolves**
 

Resolves #53 and adds extra features

**Changes**

I have added 
`if (parser.hostname === scratch.mit.edu){ //Execute Bookmarklet } else{ alert("Please click the bookmarklet on Scratch.") }`
and a few other things.
**Reason for changes**

Asked for.
**Tests**

I have tested it in my fork.

### CODE REVIEW

**Review by gosoccerboy5 — DISMISSED** [review]
looks good, except I might use `/* this kind of comment */` on the bookmarklets, since a `//` comment will cover the rest of the line

**Comment by Shluffy** [comment]
github isn't loading for me, but the '//execute bookmarklet' should either
be replaced with a function that does the bookmarklet or the bookmarklet
code. Sorry if that was unclear

**Comment by Shluffy** [comment]
also, comments in a bookmarklet as // will not work well with no linebreaks

**Comment by xItzDiamondx** [comment]
> looks good, except I might use `/* this kind of comment */` on the bookmarklets, since a `//` comment will cover the rest of the line

Fixed. Multi-line comment added.

**Comment by FunctionalMetatable** [comment]
dependabot is not needed

**Comment by xItzDiamondx** [comment]
> dependabot is not needed

That is for my fork. It'll get removed when it gets merged.

**Review by Shluffy — CHANGES_REQUESTED** [review]
1 - the `parser.hostname` check goes first
2 - the `//execute bookmarklet` should be the bookmarklet
3 - We will still need to add checks for the `/projects/*/editor` for something that only works in the editor. This could be done at a later date though.

**Comment by FunctionalMetatable** [comment]
#56 will filter out comments in the bookmarklets

**Comment by Shluffy** [comment]
> #56 will filter out comments in the bookmarklets

the problem is that it exxecutes the bookmarklet first

**Comment by Shluffy** [comment]
because #56 was merged bookmarklets.json needs to be deleted/fork needs to be updated as #56 is a major change

**Comment by xItzDiamondx** [comment]
I'm not the kind of JS person. I'll let you guys fix it. Fix it here pls: [@xItzDiamondx/Bookmarklets](https://github.com/xItzDiamondx/Bookmarklets/) Make PR

**Comment by xItzDiamondx** [comment]
I'll close it for now.

**Pull request closed without merging**
