### PR TITLE
add hostname checks

### PR DESCRIPTION
**Pull request by Shluffy**
Resolves #54

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
you can add prefix code on the bookmarklets.html page so you don't need to put it for each bookmarklet's js file

**Review by gosoccerboy5 — CHANGES_REQUESTED** [review]
lol you need quotes for `scratch.mit.edu`
wait what's `parser`? I haven't been active here recently as you've noticed, but the bookmarklet won't work since `parser is not defined`

**Comment by gosoccerboy5** [comment]
Did you mean #53 in the OP?

**Comment by FunctionalMetatable** [comment]
@gosoccerboy5 please check if my regexp is correct in bookmarklets.html

**Comment by gosoccerboy5** [comment]
> @gosoccerboy5 please check if my regexp is correct in bookmarklets.html

It seems to not work.. maybe replace `/\scratch.mit.edu/` with `/scratch.mit.edu/`..?
also strings have a builtin `.includes()` method if you need that
also you spelled "bookmarklet" as "bookmatklet"

**Comment by Shluffy** [comment]
my brain farted. yea, this won't work. so @FunctionalMetatable feel free to do this in a separate pr

**Pull request closed without merging**
