### PR TITLE
remove worthless host declaration

### PR DESCRIPTION
**Pull request by Shluffy**
**Resolves**

Resolves #

**Changes**

**Reason for changes**

**Tests**

### CODE REVIEW

**Comment by Shluffy** [comment]
**Resolves**



Resolves #-- 

**Changes**
declare host and say change it if running on fork


**Reason for changes**


because this is site, others would have repo name
**Tests**

**Comment by Shluffy** [comment]
cc @FunctionalMetatable @xItzDiamondx @gosoccerboy5

**Comment by gosoccerboy5** [comment]
what is "https://scratch-boookmarklets.github.io"

**Comment by Shluffy** [comment]
> what is "https://scratch-boookmarklets.github.io"

a typo. lemme fix that

**Comment by xItzDiamondx** [comment]
LGTM

**Review by xItzDiamondx — APPROVED** [review]

**Pull request merged**
