### PR TITLE
Patch 3: Add JSON and a few other updates

### PR DESCRIPTION
**Pull request by xItzDiamondx**
**Resolves**

Resolves none. Just some updates

**Changes**
Updates are below.

**Reason for changes**
I saw these as vulnerabilities.

**Tests**

I have tested in my fork

### CODE REVIEW

**Comment by xItzDiamondx** [comment]
cc @Shluffy @FunctionalMetatable BTW, I'm working on my science project, and my email is getting spammed by y'all commenting and committing. Please tell me if you know how to undo that.

**Comment by FunctionalMetatable** [comment]
Dependabot is not needed for this repository in any way as this is not a Node.js application.

**Comment by xItzDiamondx** [comment]
OK.

**Comment by xItzDiamondx** [comment]
Removed. Anything else to remove?

**Review by FunctionalMetatable — APPROVED** [review]
LGTM

**Review by Shluffy — APPROVED** [review]
lgtm.

**Pull request merged**
