### PR TITLE
Remove redirecttoscratchproject.js

### PR DESCRIPTION
**Pull request by Shluffy**
Kinda impractical. why would you have the project id

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
> Kinda impractical. why would you have the project id

ikr.

**Review by gosoccerboy5 — APPROVED** [review]
looks good

**Comment by Shluffy** [comment]
@ZI-Youtuber pls review/comment

**Comment by gosoccerboy5** [comment]
Since the files were deleted, maybe remove it from the json?
https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/blob/1c650010495005296fa3f7ed9e4ae8a489b4b141/bookmarklets.json#L14-L17

**Comment by Shluffy** [comment]
> Since the files were deleted, maybe remove it from the json?
> https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/blob/1c650010495005296fa3f7ed9e4ae8a489b4b141/bookmarklets.json#L14-L17

initial commit removed it from the .json, then i deleted the file. I am waiting for @ZI-Youtuber's approval - this is his bookmarklet.

**Comment by Shluffy** [comment]
however, if this gets marked stale then I will merge.

**Review by gosoccerboy5 — APPROVED** [review]
looks fine

**Comment by Shluffy** [comment]
I re-requested review as there have been changes since you approved

**Comment by gosoccerboy5** [comment]
Can I merge? Is there anything else anyone needs to check?

**Comment by Shluffy** [comment]
> Can I merge? Is there anything else anyone needs to check?

I was waiting for @ZI-Youtuber because he made this. however it doesn't seem like he is going to review it. go ahead and merge if you want.

**Comment by gosoccerboy5** [comment]
@Shluffy Do you want to delete the Shluffy-patch-1 branch?

**Pull request merged**
