### PR TITLE
Patch 6: Lots of commits plus a new bookmarklet

### PR DESCRIPTION
**Pull request by xItzDiamondx**
if going to merge, please squash/merge

### CODE REVIEW

**Comment by Shluffy** [comment]
the file [bookmarklets.json](https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/blob/master/bookmarklets/bookmarklets.json) has not been changed. You need to add the folder name of the bookmarklet (in this case `open-forkphorus`) to the .json so it displays on the site. while you are at that are you able to add `open-phosphorus` to that as well, as it is not there so it does not display on the site.

**Comment by Shluffy** [comment]
i have added the changes requested label because i did request changes, just not officialy

**Comment by FunctionalMetatable** [comment]
pleeaaaaassssseesee stop using the main branch

**Comment by xItzDiamondx** [comment]
wdym

**Comment by FunctionalMetatable** [comment]
> wdym

i mean to make a new branch in your fork/this repo **for a pull request**. After this PR please delete your fork and fork this repo again as there are too many commits in the pull request

**Review by Shluffy — APPROVED** [review]

**Pull request merged**
