### PR TITLE
fix the codeowners file

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
for some reason with the codeowners i cannot make a direct commit -_-

### CODE REVIEW

**Comment by Shluffy** [comment]
@gosoccerboy5 hasn't been contributing recently, maybe remove him as a codeowner and see if that works. Also, i don't need to be codeowner for readme.md, just the other file

**Comment by FunctionalMetatable** [comment]
> @gosoccerboy5 hasn't been contributing recently, maybe remove him as a codeowner and see if that works. Also, i don't need to be codeowner for readme.md, just the other file

it should work properly now, should request both you and @gosoccerboy5. will request me for .github files

**Comment by Shluffy** [comment]
@FunctionalMetatable no need for @xItzDiamondx to be added

**Review by Shluffy — CHANGES_REQUESTED** [review]
remove @gosoccerboy5 not really active
re-add me as codeowner `.all-contribuorsrc`

**Comment by FunctionalMetatable** [comment]
> remove @gosoccerboy5 not really active
> re-add me as codeowner `.all-contribuorsrc`

you are a codeowner for everything

**Comment by xItzDiamondx** [comment]
add me pls

**Comment by FunctionalMetatable** [comment]
> add me pls

for which?

**Comment by xItzDiamondx** [comment]
all of the webpage stuff such as script.js and styles.css and index.html. I
also made manifest.json for the website as well.

**Review by xItzDiamondx — CHANGES_REQUESTED** [review]
Please add index.html @xItzDiamondx and styles.css @xItzDiamondx and script.js @xItzDiamondx

**Review by Shluffy — APPROVED** [review]
I will probably change codeowners to be more specific later. for now, this looks good

**Comment by Shluffy** [comment]
> Please add index.html @xItzDiamondx and styles.css @xItzDiamondx and script.js @xItzDiamondx

you are for everything. Later I will specify and link comments from here for reasons. so you will be request review on stuff like that.

**Review by xItzDiamondx — APPROVED** [review]

**Comment by xItzDiamondx** [comment]
I mean, @gosoccerboy5 doesn't respond that much so we have to wait until he sees this message and approves, I think we might have to remove him as a code owner until he becomes very active again.

**Comment by Shluffy** [comment]
we need his review. Will remove from main file, then make new pr using this branch.

**Comment by Shluffy** [comment]
i realized that I could've just change it to not include admins in these rules, oh well

**Pull request merged**
