### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by xItzDiamondx**
**Resolves**
#18 

Resolves #

**Changes**
Favicon created.

**Reason for changes**
Asked for in #18 

**Tests**

Haven't been tested yet.

### CODE REVIEW

**Comment by xItzDiamondx** [comment]
Don't merge yet, I have to insert the code for the favicon.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx the favicon you chose looks good for the logo of our org

**Review by gosoccerboy5 — APPROVED** [review]
Looks good to me.

**Review by ZI-Youtuber — APPROVED** [review]

**Comment by ZI-Youtuber** [comment]
> Looks good to me.

yep

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx so merge now?

**Pull request merged**
